acts-project/actsvg

core/include/actsvg/core/svg.hpp
meta/include/actsvg/display/sheets.hpp

This adds a summary object to the `sag::object` class that allows to log some creation history in case it is needed later on.

feat: adding summary object

---

.github/workflows/build.yml
examples/basics/shapes.cpp

This fixes a build issue in the examples due to a signature mismatch for `draw::measure`.
This also adds building of examples to the `build.yml` workflow.

fix: Correct syntax for draw::measure in example, and add examples to CI workflow build

---

meta/include/actsvg/proto/cluster.hpp

This PR fixes the channel identification which was `scalar` to `unsigned int`

fix: adding cluster channel id

---

tests/meta/CMakeLists.txt
tests/meta/wire_chamber.cpp

This adds a test showcasing how to plot a multi-wire chamber - I will need to add some drift circle display as well and we can use it for segment finding debugging.
FYI  @noemina @dimitra97

feat: adding multi wire chamber display

---

meta/include/actsvg/proto/cluster.hpp
tests/meta/wire_chamber.cpp

I have inserted a possible implementation of a wire viewer, this should then be adapted in ACTS to use the `Acts::Measurement`.
It should help debugging the segment finder imported from the MS, there are several open item left:
@noemina @dimitra97 @paulgessinger

feat: inserting showcase of a possible chamber viewer

---

meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/display/grids.hpp
meta/include/actsvg/proto/grid.hpp
tests/meta/grid.cpp

This PR adds basic grid viewing of the `proto::grid` class. Nothing fancy.

feat: adding meta::grid display

---

meta/include/actsvg/display/geometry.hpp
tests/meta/surfaces.cpp

This PR adds the functionality to split surfaces in zrphi view in case they overlap with the +M_PI/-M_PI boundary, this is useful for cylindrical layer structures.
Screenshot attached, the green surface is split.

feat: split surfaces in zrphi view

---

CMakeLists.txt
meta/include/actsvg/display/geometry.hpp

Fixes visualisation issue when rectangular surfaces are split across phi boundaries. If only one vertex is beyond the boundary, you want to re-evaluate the intersection with the grid in order to properly visualise the split surfaces.

fixing visualisation issue

---

core/include/actsvg/core/draw.hpp

Fixed a bug where markers of type "x" would always use the default stroke.
**Before** (custom marker stroke style not applied)
**After**  (custom marker stroke style applied)

Added customizeable marker stroke to markers of type "x"

---

core/include/actsvg/core/draw.hpp
meta/include/actsvg/proto/surface.hpp
tests/meta/barrel_sheet.cpp
tests/meta/detector.cpp
tests/meta/endcap_sheet.cpp
tests/meta/grid.cpp
tests/meta/portal.cpp
tests/meta/wire_chamber.cpp

Add surface type (portal, sensitive, passive) to proto surface. This eases picking color schemes for the three types of surfaces in downstream projects. Also fixes a few warnings

feat: Add surface type to proto surface.

---

core/include/actsvg/core/draw.hpp
core/include/actsvg/core/views.hpp
meta/include/actsvg/display/datamodel.hpp
meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/display/helpers.hpp
meta/include/actsvg/proto/track.hpp
python/python/actsvg/__init__.py
python/python/actsvg/actsvg_uproot.py
tests/common/detector.hpp
tests/common/helix.hpp
tests/core/CMakeLists.txt
tests/core/barrel.cpp
tests/core/endcap.cpp
tests/core/polyline.cpp
tests/core/views.cpp
tests/meta/CMakeLists.txt
tests/meta/barrel_sheet.cpp
tests/meta/seeds.cpp
tests/meta/trajectories.cpp

This PR adds support for trajectory and seed displaying
It also adds `point` and `path` view options for the `view` classes in order to allow single and contour views.

feat: trajectory and seed support in xy

---

core/include/actsvg/core/style.hpp
core/include/actsvg/core/svg.hpp
meta/include/actsvg/display/datamodel.hpp
tests/common/helix.hpp
tests/meta/seeds.cpp

This PR fixes #59 by re-itroducing the explicit writing of group transforms (which was removed to avoid writing empty transforms everyhwere), instead now, transforms are always written if they are different from identity.
*Now*:
*Was*:
@niermann999

fix: group transform for arrow heads

---

core/include/actsvg/core/draw.hpp
core/include/actsvg/core/svg.hpp
meta/include/actsvg/display/materials.hpp

This fix brings back the gradient colouring.
It also changes the meaning of `._sterile` which now refers only to colouring, where `._active` refers to the viewing.

fix: gradient coloring

---

core/include/actsvg/core/draw.hpp
core/include/actsvg/core/style.hpp
core/include/actsvg/core/svg.hpp
meta/include/actsvg/display/materials.hpp
meta/include/actsvg/proto/material.hpp
tests/core/CMakeLists.txt
tests/core/gradient.cpp
tests/core/label.cpp
tests/meta/surface_materials.cpp

This adds the `style::label` struct and applies it to gradients at first.
It closes #70.

feat: adding labels and apply them

---

core/include/actsvg/core/draw.hpp
meta/include/actsvg/display/geometry.hpp
python/src/display.cpp
python/src/io.cpp

This PR is in the preparation of the summer student project 20224. It allows to correct obj read-in surfaces to be corrected to polygons with rotation and translation.

feat: adding possibility to correct at read-in

---

CMakeLists.txt
meta/include/actsvg/display/sheets.hpp

This also removes the `-Wno-unused-local-typedefs` compile flag.

fix: Avoid unused local typedef

---

meta/include/actsvg/display/geometry.hpp
python/src/proto.cpp

Finally (now), the `AnnulusBounds` can be displayed as a graph instead of vertices.

feat: annulus bounds with path (instead of vertices)

---

.github/workflows/checks.yml
meta/src/display/geometry.cpp
tests/meta/eta_lines.cpp

fix: eta lines on both sides of the detector

---

core/include/actsvg/core/svg.hpp
core/src/core/svg.cpp
tests/core/barrel.cpp
tests/core/endcap.cpp
tests/core/svg.cpp
tests/meta/barrel_sheet.cpp
tests/meta/detector.cpp

This PR allows for a custom view-box setting.
E.g. full detector
half detector:

feat: allow for a custom view box setting

---

python/src/style.cpp

There was a variable shadowing in `style.cpp`

fix: fixing variable shadowing

---

core/include/actsvg/core/svg.hpp
core/src/core/svg.cpp
python/src/io.cpp

The file clipping did not set / update the figure size. This is happening now.

feat: update clipping to respect view size

---

core/include/actsvg/core/utils.hpp
core/src/core/draw.cpp
core/src/core/style.cpp
core/src/core/utils.cpp

Fix an out of bounds exception on the gradient scale and then print material maps scale in scientific notation

Fix: Material maps scale in scientific notation

---

core/src/core/draw.cpp

some elements in a gradient box group did not have the right fill opacity.

fix: fill opacity in gradient box
