acts-project/actsvg

core/include/actsvg/core/defs.hpp
core/include/actsvg/core/draw.hpp
core/include/actsvg/core/style.hpp
core/include/actsvg/core/svg.hpp
core/include/actsvg/core/utils.hpp
meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/display/helpers.hpp
meta/include/actsvg/display/sheets.hpp
meta/include/actsvg/proto/surface.hpp
meta/include/actsvg/proto/volume.hpp
tests/core/CMakeLists.txt
tests/core/copy.cpp
tests/meta/endcap_sheet.cpp

This PR allows to create objects from templates and link to them via `xlink::href`.

Feat add copy from ref

---

core/include/actsvg/core/draw.hpp
core/include/actsvg/core/style.hpp
core/include/actsvg/core/svg.hpp
core/include/actsvg/core/utils.hpp
meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/display/helpers.hpp
meta/include/actsvg/display/sheets.hpp
meta/include/actsvg/proto/surface.hpp
meta/include/actsvg/proto/volume.hpp
tests/core/arc.cpp
tests/core/circle.cpp
tests/core/copy.cpp
tests/core/endcap.cpp
tests/core/polygon.cpp
tests/meta/barrel_sheet.cpp
tests/meta/endcap_sheet.cpp
tests/meta/surface_sheet.cpp

This changes the behaviour of the `draw::something(...)` functions, the given `transform` is applied to the object if it is raw transform, if it is from template the transform is written as a `transform` attribute.

apply transforms to raw objects

---

core/include/actsvg/core/connectors.hpp
core/include/actsvg/core/style.hpp
core/include/actsvg/core/utils.hpp
meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/display/helpers.hpp
meta/include/actsvg/display/sheets.hpp
meta/include/actsvg/proto/grid.hpp
meta/include/actsvg/styles/defaults.hpp
tests/core/endcap.cpp
tests/meta/barrel_sheet.cpp
tests/meta/endcap_sheet.cpp

This one has an almost debugged barrel / ec view --- good for testing in ACTS core

feat: sheets partly debugged

---

core/include/actsvg/core/connectors.hpp
core/include/actsvg/core/draw.hpp
core/include/actsvg/core/svg.hpp
meta/include/actsvg/display/helpers.hpp
meta/include/actsvg/display/sheets.hpp
meta/include/actsvg/proto/surface.hpp
tests/meta/barrel_sheet.cpp
tests/meta/endcap_sheet.cpp

Allowing custom aux information

feat: adding aux info field

---

core/include/actsvg/core/svg.hpp
meta/include/actsvg/display/helpers.hpp
meta/include/actsvg/display/sheets.hpp
tests/meta/endcap_sheet.cpp

This PR allows template plotting and individual plotting for Endcap structures.

feat: allow template and individual settings

---

meta/include/actsvg/display/sheets.hpp
meta/include/actsvg/proto/surface.hpp
tests/meta/surface_sheet.cpp

Nomen est omen, a special diamond shape can now be displayed as a sheet.

feat: add diamond shape

---

meta/include/actsvg/display/geometry.hpp
tests/meta/CMakeLists.txt
tests/meta/eta_lines.cpp

This PR adds eta guide lines with labels.

feat: add eta lines and unit test for it

---

core/include/actsvg/core/draw.hpp
tests/core/CMakeLists.txt
tests/core/infobox.cpp

This PR adds a new connected info box to the list of available tools

feat: info box with connection

---

core/include/actsvg/core/connectors.hpp
core/include/actsvg/core/draw.hpp
meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/display/helpers.hpp
meta/include/actsvg/display/sheets.hpp
meta/include/actsvg/proto/grid.hpp
meta/include/actsvg/proto/volume.hpp
meta/include/actsvg/styles/defaults.hpp
tests/core/CMakeLists.txt
tests/core/endcap.cpp
tests/core/infobox.cpp
tests/core/rectangle.cpp
tests/core/text.cpp
tests/meta/barrel_sheet.cpp
tests/meta/endcap_sheet.cpp
tests/meta/eta_lines.cpp

This allows double-sided views in case one can distinguish this at filling time.

feat: double sided views

---

meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/proto/surface.hpp
tests/meta/surfaces.cpp

This adds dedicated regular projective views for cylinders and discs, this is needed for portal debugging in ACTS.

projective views

---

core/include/actsvg/core/draw.hpp
tests/core/CMakeLists.txt
tests/core/arrows.cpp

This is adding a `draw::arrows(...)` method and fixes a rotation problem present.

feat: adding arrows and fix rotation problem

---

core/include/actsvg/core/style.hpp
core/include/actsvg/core/svg.hpp
core/include/actsvg/core/utils.hpp
meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/proto/portal.hpp
meta/include/actsvg/proto/volume.hpp
tests/meta/CMakeLists.txt
tests/meta/portal.cpp

This adds a portal class to the lot.

feat: adding portal class

---

meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/proto/portal.hpp
meta/include/actsvg/proto/volume.hpp
meta/include/actsvg/styles/defaults.hpp
tests/meta/detector.cpp
tests/meta/portal.cpp
tests/meta/volume.cpp

This adds the volume drawing module.

feat: adding volume drawing zr

---

meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/proto/detector.hpp
meta/include/actsvg/proto/volume.hpp
tests/meta/detector.cpp

Detector and portal drawing with attachment directions:

feat: adding detector drawing

---

meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/styles/defaults.hpp
tests/meta/volume.cpp

This adds the portal pointer views, see sag attached.

feat: adding portal views

---

core/include/actsvg/core/defs.hpp
core/include/actsvg/core/svg.hpp
core/include/actsvg/core/utils.hpp
core/include/actsvg/core/views.hpp
meta/include/actsvg/display/geometry.hpp
tests/core/views.cpp
tests/meta/surfaces.cpp

This PR is adding a scene class with view range and direction.

feat: adding scene and range

---

meta/include/actsvg/display/geometry.hpp

fix: cast to scalar for external point3

---

core/include/actsvg/core/svg.hpp
meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/display/sheets.hpp
meta/include/actsvg/proto/detector.hpp
meta/include/actsvg/proto/portal.hpp
meta/include/actsvg/proto/surface.hpp
meta/include/actsvg/proto/volume.hpp
tests/meta/detector.cpp
tests/meta/portal.cpp
tests/meta/volume.cpp

Ports in situ fixes from Acts development

port: in situ fixes of acts

---

CMakeLists.txt
meta/include/actsvg/display/datamodel.hpp
meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/display/sheets.hpp

First round of float conversion fixing and introduction of the `Wfloat-conversion` flag

fix: float conversions 

---

meta/include/actsvg/display/geometry.hpp
tests/meta/wire_chamber.cpp

The straw colouring schema was broken for straws, fixed now.

fix: adding the straw coloring schema

---

core/include/actsvg/core/connectors.hpp
meta/include/actsvg/display/grids.hpp
meta/include/actsvg/proto/grid.hpp
tests/meta/grid.cpp

Adding a new connector possibility to grids

feat: adding connection to grid view

---

meta/include/actsvg/display/grids.hpp
meta/include/actsvg/meta.hpp
meta/include/actsvg/proto/grid.hpp

Update functionality for indexed surface navigation delegates in ACTS

feat: in situ grid functionality

---

meta/include/actsvg/proto/grid.hpp

Add an explicit initialization to the proto grid enum.

ref: proto grid enum init

---

meta/include/actsvg/display/geometry.hpp

This triggered a compilation warning for ACTS

fix: use reference

---

core/include/actsvg/core/draw.hpp
core/include/actsvg/core/utils.hpp
tests/core/CMakeLists.txt
tests/core/bezier.cpp

This PR adds the functionality to draw Bézier curves, it might needs some refinement in the distance calculation for the reference points.

feat: adding bezier curve functionality

---

core/include/actsvg/core/draw.hpp
core/include/actsvg/core/style.hpp
core/include/actsvg/core/utils.hpp

Minor fix for removing transforms.

fix: transform warning

---

core/include/actsvg/core/draw.hpp
python/notebooks/primitives.ipynb
python/src/core.cpp

Introduce python bindings for primitive draw options.

feat: python primitive drawings

---

python/src/proto.cpp

This PR adds the python bindings for clusters and channels.

feat: adding cluster bindings

---

meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/proto/surface.hpp
python/notebooks/barrel.ipynb
python/notebooks/endcap.ipynb
python/python/actsvg/actsvg_json.py
python/src/display.cpp
python/src/proto.cpp

This adds the possibility to read (partly for now) - json files produced by ACTS.

feat: adding python-json  reading

---

meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/display/sheets.hpp
meta/include/actsvg/display/tools.hpp
tests/meta/surfaces.cpp

This powerful PR allows to draw annulus PRs without generating vertices
@noemina you will like this!

feat: new code for annulus bounds

---

meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/proto/surface.hpp
meta/include/actsvg/styles/defaults.hpp
meta/src/styles/defaults.cpp
python/python/actsvg/actsvg_json.py
python/src/proto.cpp
python/src/style.cpp

This PR adds the missing transform for annulus bounds, adds the names to the surfaces, and improves the python bindings for annulus.

feat: python for annulus

---

core/include/actsvg/core/draw.hpp
core/src/core/draw.cpp

image_box function now uses adapt_range to estimate range of final svg object.

feat: Updated image_box function to use adapt_range

---

core/include/actsvg/core/svg.hpp
core/src/core/draw.cpp
meta/include/actsvg/display/datamodel.hpp
meta/include/actsvg/display/geometry.hpp
meta/include/actsvg/display/sheets.hpp
meta/src/display/geometry.cpp
meta/src/display/grids.cpp
meta/src/display/materials.cpp
tests/common/playground.hpp
tests/core/text.cpp

Introduction of group constructor to save some lines of code.

feat: with commit this time

---

CMakeLists.txt
README.md

doc: update main README page

---

python/src/core.cpp
python/src/io.cpp

File was twice declared in python. This PR fixes this.

fix: remove double declaration

---

.github/workflows/build.yml

fix: update CI to include python bindings
